// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzUwqvmW-FQmui5z68hm1C1XmffpwoAMs',
    appId: '1:959161754989:web:acf373766a9e2322dba664',
    messagingSenderId: '959161754989',
    projectId: 'fir-flutter-5fe2d',
    authDomain: 'fir-flutter-5fe2d.firebaseapp.com',
    storageBucket: 'fir-flutter-5fe2d.appspot.com',
    measurementId: 'G-6X3YVWPQSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7SI71t2q73FkkrcgAii7yoKii8L0m4Y',
    appId: '1:959161754989:android:a94bdf616e2dd77fdba664',
    messagingSenderId: '959161754989',
    projectId: 'fir-flutter-5fe2d',
    storageBucket: 'fir-flutter-5fe2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUsyR4uT-7Qq7F5ifhRelKVx_Kk2PLCc',
    appId: '1:959161754989:ios:6f2f4c7bfdfa415bdba664',
    messagingSenderId: '959161754989',
    projectId: 'fir-flutter-5fe2d',
    storageBucket: 'fir-flutter-5fe2d.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
